apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app14
  labels:
    app: todo-app14
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-app14
  template:
    metadata:
      labels:
        app: todo-app14
    spec:
      imagePullSecrets:
      - name: ecr-secret
      containers:
      - name: todo-app14
        image: 183071452060.dkr.ecr.ap-northeast-2.amazonaws.com/todo-app14:latest
        ports:
        - containerPort: 5000